// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Vallés Puig, Ramon

//! Build script: regenerates VSOP87/ELP2000 tables on demand.
#[cfg(feature = "regen-data")]
use std::env;
#[cfg(feature = "regen-data")]
use std::path::PathBuf;

#[cfg(feature = "regen-data")]
#[path = "../archive/src/vsop/pipeline.rs"]
mod vsop87_build;

#[cfg(feature = "regen-data")]
#[path = "../archive/src/elp/pipeline.rs"]
mod elp2000_build;

fn main() {
    println!("cargo:rerun-if-env-changed=SIDERUST_DATASETS_DIR");
    println!("cargo:rerun-if-env-changed=SIDERUST_REGEN");
    println!("cargo:rustc-check-cfg=cfg(siderust_archive_present)");

    #[cfg(feature = "regen-data")]
    regen_tables();

    #[cfg(not(feature = "regen-data"))]
    eprintln!(
        "siderust build: using committed generated VSOP87/ELP2000 tables in src/embedded_data/. \
         Enable the `regen-data` feature and set SIDERUST_REGEN=1 to refresh them."
    );

    emit_archive_layout();
}

fn emit_archive_layout() {
    use std::env;
    use std::path::PathBuf;

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR must be set"));
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR must be set"));

    println!("cargo:rerun-if-env-changed=SIDERUST_ARCHIVE_ROOT");
    let archive_root = env::var_os("SIDERUST_ARCHIVE_ROOT")
        .map(PathBuf::from)
        .filter(|p| p.join("MANIFEST.toml").is_file())
        .or_else(|| {
            let candidates = [
                manifest_dir.join("archive"),
                manifest_dir.join("../archive"),
            ];
            candidates
                .into_iter()
                .find(|p| p.join("MANIFEST.toml").is_file())
        })
        .unwrap_or_else(|| manifest_dir.join("archive"));
    let top_manifest = archive_root.join("MANIFEST.toml");

    println!("cargo:rerun-if-changed={}", top_manifest.display());

    let archive_present = top_manifest.is_file();
    if archive_present {
        println!("cargo:rustc-cfg=siderust_archive_present");
    }

    emit_lagrange_byte_paths(&out_dir, &archive_root, archive_present);
}

fn emit_lagrange_byte_paths(
    out_dir: &std::path::Path,
    archive_root: &std::path::Path,
    archive_present: bool,
) {
    use std::fs;

    let path = out_dir.join("lagrange_paths.rs");
    let lagrange_dir = archive_root.join("src").join("lagrange").join("vsop87");
    let required = ["l1.sck", "l2.sck", "l3.sck", "l4.sck", "l5.sck"];
    let all_present = archive_present
        && required
            .iter()
            .all(|name| lagrange_dir.join(name).is_file());

    let body = if cfg!(feature = "lagrange-centers") {
        if all_present {
            let mut s = String::from(
                "/// Auto-generated by build.rs. Embeds Lagrange SCK kernels \
                 from the archive checkout.\n",
            );
            for name in required {
                let abs = lagrange_dir.join(name);
                println!("cargo:rerun-if-changed={}", abs.display());
                let upper = name.split('.').next().unwrap().to_uppercase();
                s.push_str(&format!(
                    "static {upper}_BYTES: &[u8] = include_bytes!(\"{}\");\n",
                    abs.display()
                ));
            }
            s
        } else {
            let dir_str = lagrange_dir.display().to_string().replace('\\', "\\\\");
            format!(
                "compile_error!(\"lagrange-centers feature requires the Siderust \
                 Archive at {dir_str} (missing one of l1.sck..l5.sck). Clone \
                 https://github.com/Siderust/archive and either: (a) set \
                 SIDERUST_ARCHIVE_ROOT to the checkout, (b) place an `archive/` \
                 directory next to this crate, or (c) place a sibling \
                 `../archive/` directory.\");\n"
            )
        }
    } else {
        String::from("/// Auto-generated by build.rs. `lagrange-centers` feature is disabled.\n")
    };

    if let Err(err) = fs::write(&path, body) {
        panic!(
            "failed to write lagrange_paths.rs to {}: {err}",
            path.display()
        );
    }
}

// ── `regen-data` feature ──────────────────────────────────────────────────────

/// Regenerates the committed VSOP87 and ELP2000 tables from source data.
///
/// Only runs when `SIDERUST_REGEN=1` (or `true`/`yes`) is set. Requires the
/// `regen-data` build feature so that `reqwest` is compiled only when needed.
///
/// The preferred way to invoke this is via the helper script:
///   scripts/update_generated_tables.sh
#[cfg(feature = "regen-data")]
fn regen_tables() {
    let regen = env::var("SIDERUST_REGEN")
        .map(|v| {
            let v = v.trim().to_ascii_lowercase();
            v == "1" || v == "true" || v == "yes"
        })
        .unwrap_or(false);

    if !regen {
        eprintln!(
            "siderust build (regen-data): SIDERUST_REGEN not set, skipping table regeneration."
        );
        return;
    }

    let base = datasets_base_dir();
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));
    let gen_dir = manifest_dir.join("src/embedded_data");

    eprintln!("Regenerating VSOP87 data...");
    vsop87_build::run_regen(base.join("vsop87_dataset").as_path(), &gen_dir)
        .unwrap_or_else(|e| panic!("VSOP87 codegen failed: {e}"));
    eprintln!("VSOP87 regeneration complete");

    eprintln!("Regenerating ELP2000 data...");
    elp2000_build::run_regen(base.join("elp2000_dataset").as_path(), &gen_dir)
        .unwrap_or_else(|e| panic!("ELP2000 codegen failed: {e}"));
    eprintln!("ELP2000 regeneration complete");
}

/// Returns the base directory for dataset storage.
/// Prefers `SIDERUST_DATASETS_DIR`; falls back to `OUT_DIR`.
#[cfg(feature = "regen-data")]
fn datasets_base_dir() -> PathBuf {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set by Cargo"));
    env::var_os("SIDERUST_DATASETS_DIR")
        .map(PathBuf::from)
        .unwrap_or(out_dir)
}
