// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Vallés Puig, Ramon

//! # Embedded Data — Crate-private compiled-in assets
//!
//! This module is the single source-of-truth for every dataset,
//! autogenerated table, and static coefficient array compiled into `siderust`.
//!
//! ## Two-level data model
//!
//! `siderust` separates *what datasets exist* from *how they are stored*:
//!
//! - **`siderust::datasets`** (public) — the dataset catalog. Describes each
//!   [`DatasetId`](crate::datasets::DatasetId) together with its acquisition
//!   mode (`Embedded`, `RuntimeDownload`, `ExternalProvider`). This is the
//!   API you use when you want to know *which data is available* or to
//!   manage runtime downloads.
//!
//! - **`embedded_data`** (this module, crate-private) — the storage layer.
//!   Holds the actual compiled-in byte arrays and coefficient tables.
//!   You cannot access this module directly from outside the crate; use the
//!   typed APIs in [`calculus`](crate::calculus) and [`astro`](crate::astro).
//!
//! ## What lives here
//!
//! | Sub-module / file             | Dataset                               |
//! |-------------------------------|---------------------------------------|
//! [`vsop87a`]                     | VSOP87A heliocentric rectangular       |
//! [`vsop87e`]                     | VSOP87E barycentric rectangular        |
//! [`elp_data`]                    | ELP2000-82B lunar theory               |
//! [`nut00a_tables`]               | IAU 2000A nutation series (1365 terms) |
//! [`pluto_tables`]                | Pluto abbreviated series (Meeus 1998)  |
//! [`jpl::de440`]                  | JPL DE440 build-time coefficients      |
//! [`jpl::de441`]                  | JPL DE441 build-time coefficients      |
//! `data/o3trans.dat`              | Ozone transmission table               |
//! `data/passbands/bessell1990/`   | Bessell (1990) UBVRI filter curves     |
//!
//! IERS EOP data (`finals2000A.all`) is owned by `tempoch`; access it via
//! [`crate::astro::iers_data`] (re-exports `tempoch::eop`) or directly
//! through [`crate::astro::eop::IersEop`].
//!
//! ## Visibility
//!
//! This module is `pub(crate)`.  The raw tables are an implementation detail;
//! consumers outside the crate should use the typed APIs provided by
//! [`calculus`](crate::calculus), [`astro`](crate::astro), etc.

pub(crate) mod jpl;
pub(crate) mod nut00a_tables;
pub(crate) mod pluto_tables;
