#include "tempoch_ffi.h"


#ifndef SIDERUST_FFI_H
#define SIDERUST_FFI_H

/* Warning: this file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Crossing event direction.
enum siderust_crossing_direction_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  SIDERUST_CROSSING_DIRECTION_T_RISING = 0,
  SIDERUST_CROSSING_DIRECTION_T_SETTING = 1,
};
#ifndef __cplusplus
typedef int32_t siderust_crossing_direction_t;
#endif // __cplusplus

// Culmination event kind.
enum siderust_culmination_kind_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  SIDERUST_CULMINATION_KIND_T_MAX = 0,
  SIDERUST_CULMINATION_KIND_T_MIN = 1,
};
#ifndef __cplusplus
typedef int32_t siderust_culmination_kind_t;
#endif // __cplusplus

// Status codes returned by siderust-ffi functions.
enum siderust_status_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  // Success.
  SIDERUST_STATUS_T_OK = 0,
  // A required output pointer was null.
  SIDERUST_STATUS_T_NULL_POINTER = 1,
  // Invalid or unsupported reference frame.
  SIDERUST_STATUS_T_INVALID_FRAME = 2,
  // Invalid or unsupported reference center.
  SIDERUST_STATUS_T_INVALID_CENTER = 3,
  // Coordinate transformation failed.
  SIDERUST_STATUS_T_TRANSFORM_FAILED = 4,
  // Invalid body name or parameters.
  SIDERUST_STATUS_T_INVALID_BODY = 5,
  // Star name not found in catalog.
  SIDERUST_STATUS_T_UNKNOWN_STAR = 6,
  // Invalid period (start > end).
  SIDERUST_STATUS_T_INVALID_PERIOD = 7,
  // Memory allocation failed.
  SIDERUST_STATUS_T_ALLOCATION_FAILED = 8,
  // Invalid argument or parameter.
  SIDERUST_STATUS_T_INVALID_ARGUMENT = 9,
};
#ifndef __cplusplus
typedef int32_t siderust_status_t;
#endif // __cplusplus

// Proper motion RA convention.
enum siderust_ra_convention_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  // True RA rate µα (deg/yr).
  SIDERUST_RA_CONVENTION_T_MU_ALPHA = 0,
  // Catalog rate µα★ = µα cos(δ) (deg/yr).
  SIDERUST_RA_CONVENTION_T_MU_ALPHA_STAR = 1,
};
#ifndef __cplusplus
typedef int32_t siderust_ra_convention_t;
#endif // __cplusplus

// Reference frame identifier for C interop.
enum siderust_frame_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  SIDERUST_FRAME_T_ICRS = 1,
  SIDERUST_FRAME_T_ECLIPTIC_MEAN_J2000 = 2,
  SIDERUST_FRAME_T_EQUATORIAL_MEAN_J2000 = 3,
  SIDERUST_FRAME_T_EQUATORIAL_MEAN_OF_DATE = 4,
  SIDERUST_FRAME_T_EQUATORIAL_TRUE_OF_DATE = 5,
  SIDERUST_FRAME_T_HORIZONTAL = 6,
  SIDERUST_FRAME_T_ECEF = 7,
  SIDERUST_FRAME_T_GALACTIC = 8,
  SIDERUST_FRAME_T_GCRS = 9,
  SIDERUST_FRAME_T_ECLIPTIC_OF_DATE = 10,
  SIDERUST_FRAME_T_ECLIPTIC_TRUE_OF_DATE = 11,
  SIDERUST_FRAME_T_CIRS = 12,
  SIDERUST_FRAME_T_TIRS = 13,
  SIDERUST_FRAME_T_ITRF = 14,
  SIDERUST_FRAME_T_ICRF = 15,
};
#ifndef __cplusplus
typedef int32_t siderust_frame_t;
#endif // __cplusplus

// Reference center identifier for C interop.
enum siderust_center_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  SIDERUST_CENTER_T_BARYCENTRIC = 1,
  SIDERUST_CENTER_T_HELIOCENTRIC = 2,
  SIDERUST_CENTER_T_GEOCENTRIC = 3,
  SIDERUST_CENTER_T_TOPOCENTRIC = 4,
  SIDERUST_CENTER_T_BODYCENTRIC = 5,
};
#ifndef __cplusplus
typedef int32_t siderust_center_t;
#endif // __cplusplus

// Opaque handle to a Star. Created via `siderust_star_*` functions, freed
// with `siderust_star_free`.
typedef struct SiderustStar SiderustStar;

// A threshold-crossing event.
typedef struct siderust_crossing_event_t {
  // Time of the crossing (Modified Julian Date).
  double mjd;
  // Direction of the crossing.
  siderust_crossing_direction_t direction;
} siderust_crossing_event_t;

// A culmination (local extremum in altitude) event.
typedef struct siderust_culmination_event_t {
  // Time of the culmination (Modified Julian Date).
  double mjd;
  // Altitude at the extremum in degrees.
  double altitude_deg;
  // Kind of extremum.
  siderust_culmination_kind_t kind;
} siderust_culmination_event_t;

// Geodetic position (WGS84) for C interop.
typedef struct siderust_geodetic_t {
  // Longitude in degrees (east positive).
  double lon_deg;
  // Latitude in degrees (north positive).
  double lat_deg;
  // Height above ellipsoid in metres.
  double height_m;
} siderust_geodetic_t;

// Search options for altitude computations.
typedef struct siderust_search_opts_t {
  // Time tolerance in days (default: ~1 µs = 1e-9 days).
  double time_tolerance_days;
  // Scan step in days. Set to 0 or negative to use the body's default.
  double scan_step_days;
  // Whether `scan_step_days` is valid (non-zero).
  bool has_scan_step;
} siderust_search_opts_t;

// Altitude computation query parameters.
typedef struct siderust_altitude_query_t {
  struct siderust_geodetic_t observer;
  double start_mjd;
  double end_mjd;
  double min_altitude_deg;
  double max_altitude_deg;
} siderust_altitude_query_t;

// Proper motion of a star (equatorial).
typedef struct siderust_proper_motion_t {
  // RA proper motion in degrees per Julian year.
  double pm_ra_deg_yr;
  // Dec proper motion in degrees per Julian year.
  double pm_dec_deg_yr;
  // Convention for `pm_ra`.
  siderust_ra_convention_t ra_convention;
} siderust_proper_motion_t;

// Keplerian orbital elements.
typedef struct siderust_orbit_t {
  double semi_major_axis_au;
  double eccentricity;
  double inclination_deg;
  double lon_ascending_node_deg;
  double arg_perihelion_deg;
  double mean_anomaly_deg;
  double epoch_jd;
} siderust_orbit_t;

// Planet data (value type, copyable).
typedef struct siderust_planet_t {
  double mass_kg;
  double radius_km;
  struct siderust_orbit_t orbit;
} siderust_planet_t;

// Spherical direction (lon/lat or RA/Dec) in degrees.
typedef struct siderust_spherical_dir_t {
  // Longitude / Right Ascension in degrees.
  double lon_deg;
  // Latitude / Declination in degrees.
  double lat_deg;
  // Reference frame.
  siderust_frame_t frame;
} siderust_spherical_dir_t;

// Cartesian position (x, y, z + metadata).
typedef struct siderust_cartesian_pos_t {
  double x;
  double y;
  double z;
  siderust_frame_t frame;
  siderust_center_t center;
} siderust_cartesian_pos_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns the siderust-ffi ABI version (semver-encoded: major*10000 + minor*100 + patch).
 uint32_t siderust_ffi_version(void);

// Free an array of crossing events.
 void siderust_crossings_free(struct siderust_crossing_event_t *ptr, uintptr_t count);

// Free an array of culmination events.
 void siderust_culminations_free(struct siderust_culmination_event_t *ptr, uintptr_t count);

// Compute the altitude of the Sun at a given instant (radians).

siderust_status_t siderust_sun_altitude_at(struct siderust_geodetic_t observer,
                                           double mjd,
                                           double *out_rad);

// Find periods when the Sun is above a threshold altitude.

siderust_status_t siderust_sun_above_threshold(struct siderust_geodetic_t observer,
                                               double start_mjd,
                                               double end_mjd,
                                               double threshold_deg,
                                               struct siderust_search_opts_t opts,
                                               tempoch_period_mjd_t **out,
                                               uintptr_t *count);

// Find periods when the Sun is below a threshold altitude.

siderust_status_t siderust_sun_below_threshold(struct siderust_geodetic_t observer,
                                               double start_mjd,
                                               double end_mjd,
                                               double threshold_deg,
                                               struct siderust_search_opts_t opts,
                                               tempoch_period_mjd_t **out,
                                               uintptr_t *count);

// Find threshold-crossing events for the Sun.

siderust_status_t siderust_sun_crossings(struct siderust_geodetic_t observer,
                                         double start_mjd,
                                         double end_mjd,
                                         double threshold_deg,
                                         struct siderust_search_opts_t opts,
                                         struct siderust_crossing_event_t **out,
                                         uintptr_t *count);

// Find culmination (local extrema) events for the Sun.

siderust_status_t siderust_sun_culminations(struct siderust_geodetic_t observer,
                                            double start_mjd,
                                            double end_mjd,
                                            struct siderust_search_opts_t opts,
                                            struct siderust_culmination_event_t **out,
                                            uintptr_t *count);

// Find periods when the Sun's altitude is within [min, max].

siderust_status_t siderust_sun_altitude_periods(struct siderust_altitude_query_t query,
                                                tempoch_period_mjd_t **out,
                                                uintptr_t *count);

// Compute the altitude of the Moon at a given instant (radians).

siderust_status_t siderust_moon_altitude_at(struct siderust_geodetic_t observer,
                                            double mjd,
                                            double *out_rad);

// Find periods when the Moon is above a threshold altitude.

siderust_status_t siderust_moon_above_threshold(struct siderust_geodetic_t observer,
                                                double start_mjd,
                                                double end_mjd,
                                                double threshold_deg,
                                                struct siderust_search_opts_t opts,
                                                tempoch_period_mjd_t **out,
                                                uintptr_t *count);

// Find periods when the Moon is below a threshold altitude.

siderust_status_t siderust_moon_below_threshold(struct siderust_geodetic_t observer,
                                                double start_mjd,
                                                double end_mjd,
                                                double threshold_deg,
                                                struct siderust_search_opts_t opts,
                                                tempoch_period_mjd_t **out,
                                                uintptr_t *count);

// Find threshold-crossing events for the Moon.

siderust_status_t siderust_moon_crossings(struct siderust_geodetic_t observer,
                                          double start_mjd,
                                          double end_mjd,
                                          double threshold_deg,
                                          struct siderust_search_opts_t opts,
                                          struct siderust_crossing_event_t **out,
                                          uintptr_t *count);

// Find culmination (local extrema) events for the Moon.

siderust_status_t siderust_moon_culminations(struct siderust_geodetic_t observer,
                                             double start_mjd,
                                             double end_mjd,
                                             struct siderust_search_opts_t opts,
                                             struct siderust_culmination_event_t **out,
                                             uintptr_t *count);

// Find periods when the Moon's altitude is within [min, max].

siderust_status_t siderust_moon_altitude_periods(struct siderust_altitude_query_t query,
                                                 tempoch_period_mjd_t **out,
                                                 uintptr_t *count);

// Compute the altitude of a star at a given instant (radians).

siderust_status_t siderust_star_altitude_at(const struct SiderustStar *handle,
                                            struct siderust_geodetic_t observer,
                                            double mjd,
                                            double *out_rad);

// Find periods when a star is above a threshold altitude.

siderust_status_t siderust_star_above_threshold(const struct SiderustStar *handle,
                                                struct siderust_geodetic_t observer,
                                                double start_mjd,
                                                double end_mjd,
                                                double threshold_deg,
                                                struct siderust_search_opts_t opts,
                                                tempoch_period_mjd_t **out,
                                                uintptr_t *count);

// Find periods when a star is below a threshold altitude.

siderust_status_t siderust_star_below_threshold(const struct SiderustStar *handle,
                                                struct siderust_geodetic_t observer,
                                                double start_mjd,
                                                double end_mjd,
                                                double threshold_deg,
                                                struct siderust_search_opts_t opts,
                                                tempoch_period_mjd_t **out,
                                                uintptr_t *count);

// Find crossing events for a star.

siderust_status_t siderust_star_crossings(const struct SiderustStar *handle,
                                          struct siderust_geodetic_t observer,
                                          double start_mjd,
                                          double end_mjd,
                                          double threshold_deg,
                                          struct siderust_search_opts_t opts,
                                          struct siderust_crossing_event_t **out,
                                          uintptr_t *count);

// Find culmination events for a star.

siderust_status_t siderust_star_culminations(const struct SiderustStar *handle,
                                             struct siderust_geodetic_t observer,
                                             double start_mjd,
                                             double end_mjd,
                                             struct siderust_search_opts_t opts,
                                             struct siderust_culmination_event_t **out,
                                             uintptr_t *count);

// Compute the altitude of a fixed ICRS direction at a given instant (radians).

siderust_status_t siderust_icrs_dir_altitude_at(double ra_deg,
                                                double dec_deg,
                                                struct siderust_geodetic_t observer,
                                                double mjd,
                                                double *out_rad);

// Find periods when an ICRS direction is above a threshold altitude.

siderust_status_t siderust_icrs_dir_above_threshold(double ra_deg,
                                                    double dec_deg,
                                                    struct siderust_geodetic_t observer,
                                                    double start_mjd,
                                                    double end_mjd,
                                                    double threshold_deg,
                                                    struct siderust_search_opts_t opts,
                                                    tempoch_period_mjd_t **out,
                                                    uintptr_t *count);

// Find periods when an ICRS direction is below a threshold altitude.

siderust_status_t siderust_icrs_dir_below_threshold(double ra_deg,
                                                    double dec_deg,
                                                    struct siderust_geodetic_t observer,
                                                    double start_mjd,
                                                    double end_mjd,
                                                    double threshold_deg,
                                                    struct siderust_search_opts_t opts,
                                                    tempoch_period_mjd_t **out,
                                                    uintptr_t *count);

// Look up a star from the built-in catalog by name.
//
// Supported names: "VEGA", "SIRIUS", "POLARIS", "CANOPUS", "ARCTURUS",
// "RIGEL", "BETELGEUSE", "PROCYON", "ALDEBARAN", "ALTAIR".
//
// On success, `*out` receives a newly allocated handle.
// The caller must free it with `siderust_star_free`.
 siderust_status_t siderust_star_catalog(const char *name, struct SiderustStar **out);

// Create a custom star.
//
// `name` — UTF-8 null-terminated string.
// `ra_deg`, `dec_deg` — J2000 equatorial coordinates in degrees.
// `distance_ly` — distance in light-years.
// `epoch_jd` — epoch of the given coordinates (Julian Date).
// `proper_motion` — optional: pass null for a fixed star.

siderust_status_t siderust_star_create(const char *name,
                                       double distance_ly,
                                       double mass_solar,
                                       double radius_solar,
                                       double luminosity_solar,
                                       double ra_deg,
                                       double dec_deg,
                                       double epoch_jd,
                                       const struct siderust_proper_motion_t *proper_motion,
                                       struct SiderustStar **out);

// Free a Star handle.
//
// # Safety
// The handle must have been allocated by `siderust_star_catalog` or
// `siderust_star_create`, and must not be used after this call.
 void siderust_star_free(struct SiderustStar *handle);

// Get the star's name. Copies into `buf` up to `buf_len` bytes (including NUL).
// Sets `*written` to the number of bytes written (excluding NUL).
// Returns InvalidArgument if the buffer is too small.

siderust_status_t siderust_star_name(const struct SiderustStar *handle,
                                     char *buf,
                                     uintptr_t buf_len,
                                     uintptr_t *written);

// Get the star's distance in light-years.
 double siderust_star_distance_ly(const struct SiderustStar *handle);

// Get the star's mass in solar masses.
 double siderust_star_mass_solar(const struct SiderustStar *handle);

// Get the star's radius in solar radii.
 double siderust_star_radius_solar(const struct SiderustStar *handle);

// Get the star's luminosity in solar luminosities.
 double siderust_star_luminosity_solar(const struct SiderustStar *handle);

// Get Mercury's orbital and physical parameters.
 siderust_status_t siderust_planet_mercury(struct siderust_planet_t *out);

// Get Venus's orbital and physical parameters.
 siderust_status_t siderust_planet_venus(struct siderust_planet_t *out);

// Get Earth's orbital and physical parameters.
 siderust_status_t siderust_planet_earth(struct siderust_planet_t *out);

// Get Mars's orbital and physical parameters.
 siderust_status_t siderust_planet_mars(struct siderust_planet_t *out);

// Get Jupiter's orbital and physical parameters.
 siderust_status_t siderust_planet_jupiter(struct siderust_planet_t *out);

// Get Saturn's orbital and physical parameters.
 siderust_status_t siderust_planet_saturn(struct siderust_planet_t *out);

// Get Uranus's orbital and physical parameters.
 siderust_status_t siderust_planet_uranus(struct siderust_planet_t *out);

// Get Neptune's orbital and physical parameters.
 siderust_status_t siderust_planet_neptune(struct siderust_planet_t *out);

// Transform a spherical direction from one frame to another.
//
// `jd` is required for time-dependent frames (mean/true of date, horizontal).
// For time-independent transforms between fixed-epoch frames, the JD value
// is ignored but must still be provided.
//
// Supported source/target frames: ICRS, EclipticMeanJ2000, EquatorialMeanJ2000,
// EquatorialMeanOfDate, EquatorialTrueOfDate.
//
// For conversion to Horizontal, use `siderust_spherical_dir_to_horizontal`.

siderust_status_t siderust_spherical_dir_transform_frame(double lon_deg,
                                                         double lat_deg,
                                                         siderust_frame_t src_frame,
                                                         siderust_frame_t dst_frame,
                                                         double jd,
                                                         struct siderust_spherical_dir_t *out);

// Transform a spherical direction to the horizontal (alt-az) frame.
//
// Requires an observer location (geodetic WGS84) and a Julian Date.
// Supported source frames: ICRS, EclipticMeanJ2000, EquatorialMeanJ2000,
// EquatorialMeanOfDate, EquatorialTrueOfDate.

siderust_status_t siderust_spherical_dir_to_horizontal(double lon_deg,
                                                       double lat_deg,
                                                       siderust_frame_t src_frame,
                                                       double jd,
                                                       struct siderust_geodetic_t observer,
                                                       struct siderust_spherical_dir_t *out);

// Create a geodetic position and convert to ECEF Cartesian.

siderust_status_t siderust_geodetic_to_cartesian_ecef(struct siderust_geodetic_t geodetic,
                                                      struct siderust_cartesian_pos_t *out);

// Get the Sun's barycentric position (EclipticMeanJ2000, AU) via VSOP87.
 siderust_status_t siderust_vsop87_sun_barycentric(double jd, struct siderust_cartesian_pos_t *out);

// Get the Earth's barycentric position (EclipticMeanJ2000, AU) via VSOP87.

siderust_status_t siderust_vsop87_earth_barycentric(double jd,
                                                    struct siderust_cartesian_pos_t *out);

// Get the Earth's heliocentric position (EclipticMeanJ2000, AU) via VSOP87.

siderust_status_t siderust_vsop87_earth_heliocentric(double jd,
                                                     struct siderust_cartesian_pos_t *out);

// Get the Moon's geocentric position (EclipticMeanJ2000, km) via ELP2000.
 siderust_status_t siderust_vsop87_moon_geocentric(double jd, struct siderust_cartesian_pos_t *out);

// Fill `out` with the Roque de los Muchachos observatory (La Palma, Spain).
 siderust_status_t siderust_observatory_roque_de_los_muchachos(struct siderust_geodetic_t *out);

// Fill `out` with the El Paranal observatory (Chile).
 siderust_status_t siderust_observatory_el_paranal(struct siderust_geodetic_t *out);

// Fill `out` with the Mauna Kea observatory (Hawaiʻi, USA).
 siderust_status_t siderust_observatory_mauna_kea(struct siderust_geodetic_t *out);

// Fill `out` with the La Silla observatory (Chile).
 siderust_status_t siderust_observatory_la_silla(struct siderust_geodetic_t *out);

// Create a custom geodetic position (WGS84/ECEF).

siderust_status_t siderust_geodetic_new(double lon_deg,
                                        double lat_deg,
                                        double height_m,
                                        struct siderust_geodetic_t *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SIDERUST_FFI_H */
