// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Vallés Puig, Ramon

//! # Archive — Canonical Data Store
//!
//! This module is the single source-of-truth for every dataset,
//! autogenerated table, and static coefficient array used by `siderust`.
//!
//! ## What lives here
//!
//! | Sub-module / file             | Dataset                               |
//! |-------------------------------|---------------------------------------|
//! [`vsop87a`]                     | VSOP87A heliocentric rectangular       |
//! [`vsop87e`]                     | VSOP87E barycentric rectangular        |
//! [`elp_data`]                    | ELP2000-82B lunar theory               |
//! [`nut00a_tables`]               | IAU 2000A nutation series (1365 terms) |
//! [`pluto_tables`]                | Pluto abbreviated series (Meeus 1998)  |
//! [`jpl::de440`]                  | JPL DE440 build-time coefficients      |
//! [`jpl::de441`]                  | JPL DE441 build-time coefficients      |
//! `data/o3trans.dat`              | Ozone transmission table               |
//! `data/passbands/bessell1990/`   | Bessell (1990) UBVRI filter curves     |
//!
//! IERS EOP data (`finals2000A.all`) is owned by `tempoch`; access it via
//! [`crate::astro::iers_data`] (re-exports `tempoch::eop`) or directly
//! through [`crate::astro::eop::IersEop`].
//!
//! ## Visibility
//!
//! This module is `pub(crate)`.  The raw tables are an implementation detail;
//! consumers outside the crate should use the typed APIs provided by
//! [`calculus`](crate::calculus), [`astro`](crate::astro), etc.

pub(crate) mod jpl;
pub(crate) mod nut00a_tables;
pub(crate) mod pluto_tables;
