// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Vallés Puig, Ramon

//! DE440 ephemeris backend implementing the [`Ephemeris`] trait.
//!
//! This backend is available when the `de440` Cargo feature is enabled.
//! It uses JPL DE440 Chebyshev polynomial data embedded at compile time,
//! covering the Sun, Earth-Moon barycenter and Moon (1550–2650 CE).

use super::{AuPerDay, Ephemeris};
use crate::calculus::de440::bodies;
use crate::coordinates::{
    cartesian::{Position, Velocity},
    centers::{Barycentric, Geocentric, Heliocentric},
    frames::Ecliptic,
};
use crate::targets::Target;
use crate::time::JulianDate;
use qtty::{AstronomicalUnit, Kilometer};

/// DE440 ephemeris backend (requires `de440` feature).
///
/// Zero-sized marker type. All coefficient data lives in static byte arrays
/// generated by the build script and embedded via `include_bytes!()`.
#[derive(Debug, Clone, Copy, Default)]
pub struct De440Ephemeris;

impl Ephemeris for De440Ephemeris {
    #[inline]
    fn sun_barycentric(
        jd: JulianDate,
    ) -> Target<Position<Barycentric, Ecliptic, AstronomicalUnit>> {
        bodies::sun_barycentric(jd)
    }

    #[inline]
    fn earth_barycentric(
        jd: JulianDate,
    ) -> Target<Position<Barycentric, Ecliptic, AstronomicalUnit>> {
        bodies::earth_barycentric(jd)
    }

    #[inline]
    fn earth_heliocentric(
        jd: JulianDate,
    ) -> Target<Position<Heliocentric, Ecliptic, AstronomicalUnit>> {
        bodies::earth_heliocentric(jd)
    }

    #[inline]
    fn earth_barycentric_velocity(jd: JulianDate) -> Velocity<Ecliptic, AuPerDay> {
        bodies::earth_barycentric_velocity(jd)
    }

    #[inline]
    fn moon_geocentric(jd: JulianDate) -> Position<Geocentric, Ecliptic, Kilometer> {
        bodies::moon_geocentric(jd)
    }
}
