// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Vallés Puig, Ramon

//! VSOP87 / ELP2000-82B ephemeris backend.
//!
//! This is the default (always-available) backend. It delegates to the
//! existing `Planet::vsop87*` inherent methods and `Moon::get_geo_position`.

use super::{AuPerDay, Ephemeris};
use crate::bodies::solar_system::{Earth, Moon, Sun};
use crate::coordinates::{
    cartesian::{Position, Velocity},
    centers::{Barycentric, Geocentric, Heliocentric},
    frames::Ecliptic,
};
use crate::targets::Target;
use crate::time::JulianDate;
use qtty::{AstronomicalUnit, Kilometer};

/// VSOP87 / ELP2000-82B ephemeris backend (always available).
///
/// This is a zero-sized marker type. All data lives in static arrays
/// generated by `build.rs` at compile time.
#[derive(Debug, Clone, Copy, Default)]
pub struct Vsop87Ephemeris;

impl Ephemeris for Vsop87Ephemeris {
    #[inline]
    fn sun_barycentric(
        jd: JulianDate,
    ) -> Target<Position<Barycentric, Ecliptic, AstronomicalUnit>> {
        Sun::vsop87e(jd)
    }

    #[inline]
    fn earth_barycentric(
        jd: JulianDate,
    ) -> Target<Position<Barycentric, Ecliptic, AstronomicalUnit>> {
        Earth::vsop87e(jd)
    }

    #[inline]
    fn earth_heliocentric(
        jd: JulianDate,
    ) -> Target<Position<Heliocentric, Ecliptic, AstronomicalUnit>> {
        Earth::vsop87a(jd)
    }

    #[inline]
    fn earth_barycentric_velocity(jd: JulianDate) -> Velocity<Ecliptic, AuPerDay> {
        Earth::vsop87e_vel(jd)
    }

    #[inline]
    fn moon_geocentric(jd: JulianDate) -> Position<Geocentric, Ecliptic, Kilometer> {
        Moon::get_geo_position(jd)
    }
}
