#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Vallés Puig, Ramon
#
# update_generated_tables.sh  (deprecated)
#
# Scientific dataset tables (VSOP87, ELP2000, nutation, …) are now owned and
# regenerated by the `siderust-archive` repository:
#
#   https://github.com/Siderust/archive
#
# The `regen-data` Cargo feature and this script have been removed from
# siderust.  To update the embedded Rust coefficient tables, check out the
# archive repository and follow its README / pipeline instructions.
#
echo "This script is no longer needed." >&2
echo "Scientific dataset generation has moved to https://github.com/Siderust/archive" >&2
exit 1
