// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Vallés Puig, Ramon

//! Embedded DE440 coefficient data.
//!
//! This module pulls in the binary data generated by the build script and
//! provides safe accessors for the coefficient records.
//!
//! The build script generates `de440_data.rs` which defines sub-modules
//! `sun`, `emb`, and `moon`, each containing:
//! - `INIT`, `INTLEN`, `NCOEFF`, `RSIZE`, `N_RECORDS` constants
//! - `DATA: &[u8]` — raw embedded bytes
//! - `fn record(i: usize) -> &'static [f64]` — record accessor
//!
//! ## Segment Descriptors
//!
//! [`SUN`], [`EMB`], and [`MOON`] are pre-built [`SegmentDescriptor`]s that
//! bundle each body's metadata for ergonomic use with [`eval`](super::eval).

use super::eval::SegmentDescriptor;

// Pull in the generated data module
include!(concat!(env!("OUT_DIR"), "/de440_data.rs"));

// ── Pre-built segment descriptors ────────────────────────────────────────

/// Segment descriptor for the Sun (NAIF 10 → SSB).
pub const SUN: SegmentDescriptor = SegmentDescriptor {
    init: sun::INIT,
    intlen: sun::INTLEN,
    ncoeff: sun::NCOEFF,
    n_records: sun::N_RECORDS,
    record_fn: sun::record,
};

/// Segment descriptor for the Earth-Moon Barycenter (NAIF 3 → SSB).
pub const EMB: SegmentDescriptor = SegmentDescriptor {
    init: emb::INIT,
    intlen: emb::INTLEN,
    ncoeff: emb::NCOEFF,
    n_records: emb::N_RECORDS,
    record_fn: emb::record,
};

/// Segment descriptor for the Moon (NAIF 301 → EMB).
pub const MOON: SegmentDescriptor = SegmentDescriptor {
    init: moon::INIT,
    intlen: moon::INTLEN,
    ncoeff: moon::NCOEFF,
    n_records: moon::N_RECORDS,
    record_fn: moon::record,
};
