// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Vallés Puig, Ramon

//! Embedded DE440 coefficient data.
//!
//! This module pulls in the binary data generated by the build script and
//! provides safe accessors for the coefficient records.
//!
//! The build script generates `de440_data.rs` which defines sub-modules
//! `sun`, `emb`, and `moon`, each containing:
//! - `INIT`, `INTLEN`, `NCOEFF`, `RSIZE`, `N_RECORDS` constants
//! - `DATA: &[u8]` — raw embedded bytes
//! - `fn record(i: usize) -> &[f64]` — record accessor

// Pull in the generated data module
include!(concat!(env!("OUT_DIR"), "/de440_data.rs"));
