name: Siderust CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  checks: write

concurrency:
  group: coverage-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test-and-coverage:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust (nightly + llvm-tools)
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov
          version: latest

      - name: Coverage (run, no report)
        run: cargo llvm-cov --workspace --all-features --doctests --no-report

      - name: Coverage (Cobertura XML)
        run: cargo llvm-cov report --cobertura --output-path coverage.xml

      - name: Coverage (HTML)
        run: cargo llvm-cov report --html --output-dir coverage_html

      - name: Build coverage summary (Markdown)
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          format: markdown
          output: file

      - name: Publish to Job Summary
        run: cat code-coverage-results.md >> "$GITHUB_STEP_SUMMARY"

      - name: Coverage check (gate)
        uses: insightsengineering/coverage-action@v3
        with:
          path: coverage.xml
          threshold: 1 #TODO: set value!
          fail: true
          publish: false
          diff: false

      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage_html
          retention-days: 7
