name: Siderust CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust (stable + llvm-tools)
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: llvm-tools-preview

      - name: Build
        run: cargo build --lib --locked

      - name: Test
        run: cargo test --all-features --locked

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Run coverage
        run: |
          cargo llvm-cov --workspace --all-features --doctests \
            --cobertura --output-path coverage.xml \
            --html --output-dir coverage_html \
            --text | tee coverage.txt

      - name: Build coverage summary (Markdown)
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          format: markdown
          output: file

      - name: Publish to Job Summary
        run: cat code-coverage-results.md >> "$GITHUB_STEP_SUMMARY"

      - name: Coverage check (gate)
        uses: insightsengineering/coverage-action@v3
        with:
          path: coverage.xml
          threshold: 80
          fail: true
          publish: false

      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage_html
          retention-days: 7
